server:
  port: 8030
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/BookStoreWeb
    username: postgres
    password: 21062004
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: UTF-8
    cache: false
  web:
    resources:
      static-locations: classpath:/static/


